makelab: server/server.c client/client.c
	rm -f server/s
	rm -f client/c
	gcc server/server.c -o server/s
	gcc client/client.c -o client/c
	rm -f client/name.txt 
	rm -f client/photo.jpg 
	rm -f client/*.txt

